### ISSUE TITLE
Alias of an external type with an any fallback produces non-compiling code

### ISSUE THREAD

**Issue by tabboud** [palantir/conjure-go#251]
## What happened?

An alias definition for an external type that uses `any` as the fallback will generate serde methods for the type. Since the type is `any`, which maps to an `interface{}`, methods cannot be added to the type and thus results in a compile time error.

Here is a short repro of the issue:

Conjure definition
```yml
types:
  imports:
    ExternalLong:
      base-type: any
      external:
        java: java.lang.Long
  definitions:
    default-package: api
    objects:
      LongAlias:
        alias: ExternalLong
```

When compiled with conjure-go >= `v6.6.0` the following will be produced:
```go
// This file was generated by Conjure and should not be manually edited.

package api

import (
	safejson "github.com/palantir/pkg/safejson"
	safeyaml "github.com/palantir/pkg/safeyaml"
)

type LongAlias interface{}

func (a LongAlias) MarshalJSON() ([]byte, error) {
	return safejson.Marshal(interface{}(a))
}

func (a *LongAlias) UnmarshalJSON(data []byte) error {
	var rawLongAlias interface{}
	if err := safejson.Unmarshal(data, &rawLongAlias); err != nil {
		return err
	}
	*a = LongAlias(rawLongAlias)
	return nil
}

func (a LongAlias) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(a)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (a *LongAlias) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&a)
}
```

## What did you want to happen?

Since the fallback type is an interface, no methods should be serde methods should be generated, so we would result in just the type definition.
```go
// This file was generated by Conjure and should not be manually edited.

package api

type LongAlias interface{}
```

The behavior above matches what was generated prior to conjure-go `v6.6.0`
