### ISSUE TITLE
Runtime panic occurs if there are multiple Conjure errors with the same name

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-go#415]
## What did you do?
1. Publish the following Conjure definition (which will be referred to as `common-service.conjure.json`):

```
types:
  definitions:
    default-package: com.palantir.test
    errors:
      EntityNotFound:
        namespace: V6
        code: NOT_FOUND
        docs: Thrown when the provided entity ID is not found
        safe-args:
          entityId: string
```

2. Create module `github.com/palantir/test-library-module` that generates code using the `common-service.conjure.json` definition and references the generated code
3. Create module `github.com/palantir/test-service-module` that generates code using the `common-service.conjure.json` definition and references the generated code AND that has `github.com/palantir/test-library-module` as a module dependency in `go.mod`
4. Run the `github.com/palantir/test-service-module`

## What happened?
The program crashes on startup with the following error:

```
panic: ErrorName V6:EntityNotFound already registered as v6.EntityNotFound

goroutine 1 [running]:
github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors.RegisterErrorType({0x10237d60e, 0x11}, {0x10272f050?, 0x1021e2960})
```

## What did you want to happen?
Program should start normally
