### ISSUE TITLE
server generation generates un-compilable code when using a string alias struct as a path arg

### ISSUE THREAD

**Issue by michaelchen01** [palantir/conjure-go#47]
Go version: 1.11.5

Conjure definition:
```
getImport:
    http: GET /{importId}
    args:
      importId:
        type: imports.ImportId
        param-type: path
    returns: imports.Import
```
Generated code (strconv.Quote returns a single argument):
```
var importId imports.ImportId
if importIdQuote, err := strconv.Quote(importIdStr); err != nil {
	return werror.Wrap(err, "failed to quote argument", werror.SafeParam("argName", "importId"), werror.SafeParam("argType", "imports.ImportId"))
} else {
	if err := safejson.Unmarshal([]byte(importIdQuote), &importId); err != nil {
		return werror.Wrap(err, "failed to unmarshal argument", werror.SafeParam("argName", "importId"), werror.SafeParam("argType", "imports.ImportId"))
	}
}
```
