### ISSUE TITLE
Generated union code panics when marshalling union type with `nil` member

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-go#523]
## What happened?
Generate Conjure using the following definition:

```
types:
  definitions:
    default-package: com.palantir.apollo.catalog.api.module
    objects:
      VariableSpec:
        union:
          string: StringVariable

      StringVariable:
        fields:
          defaultValue:
            type: optional<string>
            safety: unsafe
          description:
            type: string
            safety: unsafe
```

(from https://github.pb/foundry/apollo-catalog/blob/develop/apollo-catalog-api/src/main/conjure/ModuleService.yml#L107-L118)

This generates the following Go:

```go
type VariableSpec struct {
	typ    string
	string *StringVariable
}

type variableSpecDeserializer struct {
	Type   string          `json:"type"`
	String *StringVariable `json:"string"`
}

func (u *variableSpecDeserializer) toStruct() VariableSpec {
	return VariableSpec{typ: u.Type, string: u.String}
}

func (u *VariableSpec) toSerializer() (interface{}, error) {
	switch u.typ {
	default:
		return nil, fmt.Errorf("unknown type %s", u.typ)
	case "string":
		return struct {
			Type   string         `json:"type"`
			String StringVariable `json:"string"`
		}{Type: "string", String: *u.string}, nil
	}
}
```

Note the `String: *u.string` at line 267 (https://github.pb/deployability/apollo-cli/blob/c66d938a2da8d1ec054f9d8a84ab21c0f08f5795/internal/generated/conjure/apollo_catalog_api/apollo/catalog/api/module/unions.conjure.go#L267) -- because this is a dereference of `u.string`, if `StringVariable` is `nil`, this will panic.

Although it's not possible to construct a `nil` value via constructors, it is via JSON unmarshal. Thus, the following code panics:

```
	var spec module.VariableSpec

	err := json.Unmarshal([]byte(`{"type": "string"}`), &spec)
	require.NoError(t, err)

	_, err = spec.MarshalJSON()
	require.NoError(t, err)
```

## What did you want to happen?
Either:

1. If `StringValue` cannot be `nil` in the Union type, then the `json.Unmarshal` call should return an error
2. Otherwise, the `MarshalJSON` code should produce valid JSON or produce an error (but not panic)

From my reading of the code, it seems like (1) is more correct -- in the union type definition, the `StringVariable` definition is not optional, so it being `nil` should not be allowed (the expected unmarshal should produce a `VariableSpec` with a non-`nil` `StringVariable` that has `nil`/empty content
