### ISSUE TITLE
Lists and Sets as query parameters breaks server code generation

### ISSUE THREAD

**Issue by jdhenke** [palantir/conjure-go#62]
## What happened?

Server code generation breaks with the following error if you use a `list` or `set` argument for a `query` `param-type`:

```
Error: failed to generate Conjure: failed to generate AST for service FooService: can not assign string expression to list type
```

To reproduce, use this conjure yaml:

```yaml
types:
  definitions:
    objects:
services:
  FooService:
    name: "Foo Service"
    package: com.palantir.foo
    base-path: /foo
    endpoints:
      bar:
        http: GET /bar
        args:
          listOfStrings:
            param-type: query
            type: list<string> # this breaks
```

Which produces the following conjure IR:

```json
{
  "version" : 1,
  "errors" : [ ],
  "types" : [ ],
  "services" : [ {
    "serviceName" : {
      "name" : "FooService",
      "package" : "com.palantir.foo"
    },
    "endpoints" : [ {
      "endpointName" : "bar",
      "httpMethod" : "GET",
      "httpPath" : "/foo/bar",
      "args" : [ {
        "argName" : "listOfStrings",
        "type" : {
          "type" : "list",
          "list" : {
            "itemType" : {
              "type" : "primitive",
              "primitive" : "STRING"
            }
          }
        },
        "paramType" : {
          "type" : "query",
          "query" : {
            "paramId" : "listOfStrings"
          }
        },
        "markers" : [ ]
      } ],
      "markers" : [ ]
    } ]
  } ]
}
```

Now reproduce the failure by running `conjure-go` directly with and without server code generation:

```
# works fine without generating the server code
$ go run main.go --output /tmp/ /tmp/conjure.json

# breaks if you generate the server code
$ go run main.go --output /tmp/ --server /tmp/conjure.json
Error: failed to generate Conjure: failed to generate AST for service FooService: can not assign string expression to list type
exit status 1
```

## What did you want to happen?

Server code generation should work in this case.
