### ISSUE TITLE
UUID in errors causes package and parameter conflict

### ISSUE THREAD

**Issue by chris05atm** [palantir/conjure-go#78]
## What happened?

Define a conjure errors type like this:

```
types:
  definitions:
    default-package: com.foo.bar
    errors:
      CollisionError:
        namespace: MyNameSpace
        code: PERMISSION_DENIED
        safe-args:
          uuid: optional<uuid>
```

This generates code like this:

```
// NewCollisionError returns new instance of CollisionError error.
func NewCollisionError(uuid *uuid.UUID) *CollisionError {
	return &CollisionError{errorInstanceID: uuid.NewUUID(), collisionError: collisionError{Uuid: uuid}}
}
```

Parameter name `uuid` collides with the package `uuid` and results in the parameter's function being called instead of the `uuid` package's `NewUUID` function.

Compile errors result.

## What did you want to happen?

The parameter name should be munged to something like uuidArg or something (to avoid collision).
