### ISSUE TITLE
Error parameter with the same name as the error causes compile breaks

### ISSUE THREAD

**Issue by advayakrishna** [palantir/conjure-go#96]
## What happened?
Defining an error with a parameter that has the same name as the error cause a break in generated code, example below:

```
InvalidRids:
  namespace: Example
  code: INVALID_ARGUMENT
  docs: |
    Thrown when an operation is attempted on invalid RIDs
  safe-args:
    invalidRids: set<rid>
```

This generates code that looks like this:
```
// NewInvalidRids returns new instance of InvalidRids error.
func NewInvalidRids(invalidRids []rid.ResourceIdentifier) *InvalidRids {
	return &InvalidRids{errorInstanceID: uuid.NewUUID(), invalidRids: invalidRids{InvalidRids: foo}}
}

// InvalidRids is an error type.
//
// Thrown when an operation is attempted on invalid RIDs
type InvalidRids struct {
	errorInstanceID uuid.UUID
	invalidRids
}
```

## What did you want to happen?
Would prefer if the generated code renamed the parameter to avoid the compile break.
